// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReleaseCheckerPort creates a new instance of MockReleaseCheckerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReleaseCheckerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReleaseCheckerPort {
	mock := &MockReleaseCheckerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReleaseCheckerPort is an autogenerated mock type for the ReleaseCheckerPort type
type MockReleaseCheckerPort struct {
	mock.Mock
}

type MockReleaseCheckerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReleaseCheckerPort) EXPECT() *MockReleaseCheckerPort_Expecter {
	return &MockReleaseCheckerPort_Expecter{mock: &_m.Mock}
}

// LatestReleaseTag provides a mock function for the type MockReleaseCheckerPort
func (_mock *MockReleaseCheckerPort) LatestReleaseTag(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestReleaseTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReleaseCheckerPort_LatestReleaseTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestReleaseTag'
type MockReleaseCheckerPort_LatestReleaseTag_Call struct {
	*mock.Call
}

// LatestReleaseTag is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReleaseCheckerPort_Expecter) LatestReleaseTag(ctx any) *MockReleaseCheckerPort_LatestReleaseTag_Call {
	return &MockReleaseCheckerPort_LatestReleaseTag_Call{Call: _e.mock.On("LatestReleaseTag", ctx)}
}

func (_c *MockReleaseCheckerPort_LatestReleaseTag_Call) Run(run func(ctx context.Context)) *MockReleaseCheckerPort_LatestReleaseTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReleaseCheckerPort_LatestReleaseTag_Call) Return(s string, err error) *MockReleaseCheckerPort_LatestReleaseTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockReleaseCheckerPort_LatestReleaseTag_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockReleaseCheckerPort_LatestReleaseTag_Call {
	_c.Call.Return(run)
	return _c
}
