// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSidebarLoggerPort creates a new instance of MockSidebarLoggerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSidebarLoggerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSidebarLoggerPort {
	mock := &MockSidebarLoggerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSidebarLoggerPort is an autogenerated mock type for the SidebarLoggerPort type
type MockSidebarLoggerPort struct {
	mock.Mock
}

type MockSidebarLoggerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSidebarLoggerPort) EXPECT() *MockSidebarLoggerPort_Expecter {
	return &MockSidebarLoggerPort_Expecter{mock: &_m.Mock}
}

// WithSidebarLogger provides a mock function for the type MockSidebarLoggerPort
func (_mock *MockSidebarLoggerPort) WithSidebarLogger(logger ports.LoggerPort) ports.SidebarPort {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for WithSidebarLogger")
	}

	var r0 ports.SidebarPort
	if returnFunc, ok := ret.Get(0).(func(ports.LoggerPort) ports.SidebarPort); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SidebarPort)
		}
	}
	return r0
}

// MockSidebarLoggerPort_WithSidebarLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSidebarLogger'
type MockSidebarLoggerPort_WithSidebarLogger_Call struct {
	*mock.Call
}

// WithSidebarLogger is a helper method to define mock.On call
//   - logger ports.LoggerPort
func (_e *MockSidebarLoggerPort_Expecter) WithSidebarLogger(logger any) *MockSidebarLoggerPort_WithSidebarLogger_Call {
	return &MockSidebarLoggerPort_WithSidebarLogger_Call{Call: _e.mock.On("WithSidebarLogger", logger)}
}

func (_c *MockSidebarLoggerPort_WithSidebarLogger_Call) Run(run func(logger ports.LoggerPort)) *MockSidebarLoggerPort_WithSidebarLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.LoggerPort
		if args[0] != nil {
			arg0 = args[0].(ports.LoggerPort)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSidebarLoggerPort_WithSidebarLogger_Call) Return(sidebarPort ports.SidebarPort) *MockSidebarLoggerPort_WithSidebarLogger_Call {
	_c.Call.Return(sidebarPort)
	return _c
}

func (_c *MockSidebarLoggerPort_WithSidebarLogger_Call) RunAndReturn(run func(logger ports.LoggerPort) ports.SidebarPort) *MockSidebarLoggerPort_WithSidebarLogger_Call {
	_c.Call.Return(run)
	return _c
}
