// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessPort creates a new instance of MockProcessPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessPort {
	mock := &MockProcessPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessPort is an autogenerated mock type for the ProcessPort type
type MockProcessPort struct {
	mock.Mock
}

type MockProcessPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessPort) EXPECT() *MockProcessPort_Expecter {
	return &MockProcessPort_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockProcessPort
func (_mock *MockProcessPort) Exec(ctx context.Context, name string, args []string) (ports.Result, error) {
	ret := _mock.Called(ctx, name, args)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 ports.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (ports.Result, error)); ok {
		return returnFunc(ctx, name, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ports.Result); ok {
		r0 = returnFunc(ctx, name, args)
	} else {
		r0 = ret.Get(0).(ports.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, name, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessPort_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockProcessPort_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args []string
func (_e *MockProcessPort_Expecter) Exec(ctx interface{}, name interface{}, args interface{}) *MockProcessPort_Exec_Call {
	return &MockProcessPort_Exec_Call{Call: _e.mock.On("Exec", ctx, name, args)}
}

func (_c *MockProcessPort_Exec_Call) Run(run func(ctx context.Context, name string, args []string)) *MockProcessPort_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessPort_Exec_Call) Return(result ports.Result, err error) *MockProcessPort_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockProcessPort_Exec_Call) RunAndReturn(run func(ctx context.Context, name string, args []string) (ports.Result, error)) *MockProcessPort_Exec_Call {
	_c.Call.Return(run)
	return _c
}
