// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSidebarRefresherPort creates a new instance of MockSidebarRefresherPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSidebarRefresherPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSidebarRefresherPort {
	mock := &MockSidebarRefresherPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSidebarRefresherPort is an autogenerated mock type for the SidebarRefresherPort type
type MockSidebarRefresherPort struct {
	mock.Mock
}

type MockSidebarRefresherPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSidebarRefresherPort) EXPECT() *MockSidebarRefresherPort_Expecter {
	return &MockSidebarRefresherPort_Expecter{mock: &_m.Mock}
}

// RefreshAllSidebars provides a mock function for the type MockSidebarRefresherPort
func (_mock *MockSidebarRefresherPort) RefreshAllSidebars(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAllSidebars")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSidebarRefresherPort_RefreshAllSidebars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAllSidebars'
type MockSidebarRefresherPort_RefreshAllSidebars_Call struct {
	*mock.Call
}

// RefreshAllSidebars is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSidebarRefresherPort_Expecter) RefreshAllSidebars(ctx interface{}) *MockSidebarRefresherPort_RefreshAllSidebars_Call {
	return &MockSidebarRefresherPort_RefreshAllSidebars_Call{Call: _e.mock.On("RefreshAllSidebars", ctx)}
}

func (_c *MockSidebarRefresherPort_RefreshAllSidebars_Call) Run(run func(ctx context.Context)) *MockSidebarRefresherPort_RefreshAllSidebars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSidebarRefresherPort_RefreshAllSidebars_Call) Return(err error) *MockSidebarRefresherPort_RefreshAllSidebars_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSidebarRefresherPort_RefreshAllSidebars_Call) RunAndReturn(run func(ctx context.Context) error) *MockSidebarRefresherPort_RefreshAllSidebars_Call {
	_c.Call.Return(run)
	return _c
}
