// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/core/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystemColorSchemePort creates a new instance of MockSystemColorSchemePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemColorSchemePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemColorSchemePort {
	mock := &MockSystemColorSchemePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystemColorSchemePort is an autogenerated mock type for the SystemColorSchemePort type
type MockSystemColorSchemePort struct {
	mock.Mock
}

type MockSystemColorSchemePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemColorSchemePort) EXPECT() *MockSystemColorSchemePort_Expecter {
	return &MockSystemColorSchemePort_Expecter{mock: &_m.Mock}
}

// CurrentPreference provides a mock function for the type MockSystemColorSchemePort
func (_mock *MockSystemColorSchemePort) CurrentPreference(ctx context.Context) (config.SystemColorSchemePreference, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentPreference")
	}

	var r0 config.SystemColorSchemePreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (config.SystemColorSchemePreference, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) config.SystemColorSchemePreference); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(config.SystemColorSchemePreference)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemColorSchemePort_CurrentPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPreference'
type MockSystemColorSchemePort_CurrentPreference_Call struct {
	*mock.Call
}

// CurrentPreference is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemColorSchemePort_Expecter) CurrentPreference(ctx any) *MockSystemColorSchemePort_CurrentPreference_Call {
	return &MockSystemColorSchemePort_CurrentPreference_Call{Call: _e.mock.On("CurrentPreference", ctx)}
}

func (_c *MockSystemColorSchemePort_CurrentPreference_Call) Run(run func(ctx context.Context)) *MockSystemColorSchemePort_CurrentPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemColorSchemePort_CurrentPreference_Call) Return(systemColorSchemePreference config.SystemColorSchemePreference, err error) *MockSystemColorSchemePort_CurrentPreference_Call {
	_c.Call.Return(systemColorSchemePreference, err)
	return _c
}

func (_c *MockSystemColorSchemePort_CurrentPreference_Call) RunAndReturn(run func(ctx context.Context) (config.SystemColorSchemePreference, error)) *MockSystemColorSchemePort_CurrentPreference_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockSystemColorSchemePort
func (_mock *MockSystemColorSchemePort) Watch(ctx context.Context) (<-chan config.SystemColorSchemePreference, <-chan error, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan config.SystemColorSchemePreference
	var r1 <-chan error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan config.SystemColorSchemePreference, <-chan error, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan config.SystemColorSchemePreference); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan config.SystemColorSchemePreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSystemColorSchemePort_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockSystemColorSchemePort_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemColorSchemePort_Expecter) Watch(ctx any) *MockSystemColorSchemePort_Watch_Call {
	return &MockSystemColorSchemePort_Watch_Call{Call: _e.mock.On("Watch", ctx)}
}

func (_c *MockSystemColorSchemePort_Watch_Call) Run(run func(ctx context.Context)) *MockSystemColorSchemePort_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemColorSchemePort_Watch_Call) Return(systemColorSchemePreferenceCh <-chan config.SystemColorSchemePreference, errCh <-chan error, err error) *MockSystemColorSchemePort_Watch_Call {
	_c.Call.Return(systemColorSchemePreferenceCh, errCh, err)
	return _c
}

func (_c *MockSystemColorSchemePort_Watch_Call) RunAndReturn(run func(ctx context.Context) (<-chan config.SystemColorSchemePreference, <-chan error, error)) *MockSystemColorSchemePort_Watch_Call {
	_c.Call.Return(run)
	return _c
}
