// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLockerPort creates a new instance of MockLockerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLockerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLockerPort {
	mock := &MockLockerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLockerPort is an autogenerated mock type for the LockerPort type
type MockLockerPort struct {
	mock.Mock
}

type MockLockerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLockerPort) EXPECT() *MockLockerPort_Expecter {
	return &MockLockerPort_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type MockLockerPort
func (_mock *MockLockerPort) Acquire(ctx context.Context, key string) (ports.LockHandle, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 ports.LockHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.LockHandle, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.LockHandle); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.LockHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLockerPort_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockLockerPort_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLockerPort_Expecter) Acquire(ctx any, key any) *MockLockerPort_Acquire_Call {
	return &MockLockerPort_Acquire_Call{Call: _e.mock.On("Acquire", ctx, key)}
}

func (_c *MockLockerPort_Acquire_Call) Run(run func(ctx context.Context, key string)) *MockLockerPort_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLockerPort_Acquire_Call) Return(lockHandle ports.LockHandle, err error) *MockLockerPort_Acquire_Call {
	_c.Call.Return(lockHandle, err)
	return _c
}

func (_c *MockLockerPort_Acquire_Call) RunAndReturn(run func(ctx context.Context, key string) (ports.LockHandle, error)) *MockLockerPort_Acquire_Call {
	_c.Call.Return(run)
	return _c
}
