// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryPort creates a new instance of MockQueryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryPort {
	mock := &MockQueryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryPort is an autogenerated mock type for the QueryPort type
type MockQueryPort struct {
	mock.Mock
}

type MockQueryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryPort) EXPECT() *MockQueryPort_Expecter {
	return &MockQueryPort_Expecter{mock: &_m.Mock}
}

// CurrentPanePath provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) CurrentPanePath(ctx context.Context, clientID string) (string, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentPanePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_CurrentPanePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPanePath'
type MockQueryPort_CurrentPanePath_Call struct {
	*mock.Call
}

// CurrentPanePath is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockQueryPort_Expecter) CurrentPanePath(ctx any, clientID any) *MockQueryPort_CurrentPanePath_Call {
	return &MockQueryPort_CurrentPanePath_Call{Call: _e.mock.On("CurrentPanePath", ctx, clientID)}
}

func (_c *MockQueryPort_CurrentPanePath_Call) Run(run func(ctx context.Context, clientID string)) *MockQueryPort_CurrentPanePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryPort_CurrentPanePath_Call) Return(s string, err error) *MockQueryPort_CurrentPanePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQueryPort_CurrentPanePath_Call) RunAndReturn(run func(ctx context.Context, clientID string) (string, error)) *MockQueryPort_CurrentPanePath_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) ListClients(ctx context.Context) ([]ports.ClientSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []ports.ClientSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.ClientSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.ClientSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.ClientSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockQueryPort_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryPort_Expecter) ListClients(ctx any) *MockQueryPort_ListClients_Call {
	return &MockQueryPort_ListClients_Call{Call: _e.mock.On("ListClients", ctx)}
}

func (_c *MockQueryPort_ListClients_Call) Run(run func(ctx context.Context)) *MockQueryPort_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryPort_ListClients_Call) Return(clientSnapshots []ports.ClientSnapshot, err error) *MockQueryPort_ListClients_Call {
	_c.Call.Return(clientSnapshots, err)
	return _c
}

func (_c *MockQueryPort_ListClients_Call) RunAndReturn(run func(ctx context.Context) ([]ports.ClientSnapshot, error)) *MockQueryPort_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) ListSessions(ctx context.Context) ([]ports.SessionSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []ports.SessionSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.SessionSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.SessionSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.SessionSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockQueryPort_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryPort_Expecter) ListSessions(ctx any) *MockQueryPort_ListSessions_Call {
	return &MockQueryPort_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx)}
}

func (_c *MockQueryPort_ListSessions_Call) Run(run func(ctx context.Context)) *MockQueryPort_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryPort_ListSessions_Call) Return(sessionSnapshots []ports.SessionSnapshot, err error) *MockQueryPort_ListSessions_Call {
	_c.Call.Return(sessionSnapshots, err)
	return _c
}

func (_c *MockQueryPort_ListSessions_Call) RunAndReturn(run func(ctx context.Context) ([]ports.SessionSnapshot, error)) *MockQueryPort_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// PaneSize provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) PaneSize(ctx context.Context, paneID string) (ports.PaneSize, error) {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for PaneSize")
	}

	var r0 ports.PaneSize
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PaneSize, error)); ok {
		return returnFunc(ctx, paneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PaneSize); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Get(0).(ports.PaneSize)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, paneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_PaneSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaneSize'
type MockQueryPort_PaneSize_Call struct {
	*mock.Call
}

// PaneSize is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockQueryPort_Expecter) PaneSize(ctx any, paneID any) *MockQueryPort_PaneSize_Call {
	return &MockQueryPort_PaneSize_Call{Call: _e.mock.On("PaneSize", ctx, paneID)}
}

func (_c *MockQueryPort_PaneSize_Call) Run(run func(ctx context.Context, paneID string)) *MockQueryPort_PaneSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryPort_PaneSize_Call) Return(paneSize ports.PaneSize, err error) *MockQueryPort_PaneSize_Call {
	_c.Call.Return(paneSize, err)
	return _c
}

func (_c *MockQueryPort_PaneSize_Call) RunAndReturn(run func(ctx context.Context, paneID string) (ports.PaneSize, error)) *MockQueryPort_PaneSize_Call {
	_c.Call.Return(run)
	return _c
}

// ServerID provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) ServerID(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ServerID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_ServerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerID'
type MockQueryPort_ServerID_Call struct {
	*mock.Call
}

// ServerID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryPort_Expecter) ServerID(ctx any) *MockQueryPort_ServerID_Call {
	return &MockQueryPort_ServerID_Call{Call: _e.mock.On("ServerID", ctx)}
}

func (_c *MockQueryPort_ServerID_Call) Run(run func(ctx context.Context)) *MockQueryPort_ServerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryPort_ServerID_Call) Return(s string, err error) *MockQueryPort_ServerID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQueryPort_ServerID_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockQueryPort_ServerID_Call {
	_c.Call.Return(run)
	return _c
}

// SessionPath provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) SessionPath(ctx context.Context, sessionName string) (string, error) {
	ret := _mock.Called(ctx, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for SessionPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, sessionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, sessionName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_SessionPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionPath'
type MockQueryPort_SessionPath_Call struct {
	*mock.Call
}

// SessionPath is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
func (_e *MockQueryPort_Expecter) SessionPath(ctx any, sessionName any) *MockQueryPort_SessionPath_Call {
	return &MockQueryPort_SessionPath_Call{Call: _e.mock.On("SessionPath", ctx, sessionName)}
}

func (_c *MockQueryPort_SessionPath_Call) Run(run func(ctx context.Context, sessionName string)) *MockQueryPort_SessionPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryPort_SessionPath_Call) Return(s string, err error) *MockQueryPort_SessionPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQueryPort_SessionPath_Call) RunAndReturn(run func(ctx context.Context, sessionName string) (string, error)) *MockQueryPort_SessionPath_Call {
	_c.Call.Return(run)
	return _c
}

// SessionPaths provides a mock function for the type MockQueryPort
func (_mock *MockQueryPort) SessionPaths(ctx context.Context, sessionNames []string) (map[string]string, error) {
	ret := _mock.Called(ctx, sessionNames)

	if len(ret) == 0 {
		panic("no return value specified for SessionPaths")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return returnFunc(ctx, sessionNames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = returnFunc(ctx, sessionNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, sessionNames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryPort_SessionPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionPaths'
type MockQueryPort_SessionPaths_Call struct {
	*mock.Call
}

// SessionPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionNames []string
func (_e *MockQueryPort_Expecter) SessionPaths(ctx any, sessionNames any) *MockQueryPort_SessionPaths_Call {
	return &MockQueryPort_SessionPaths_Call{Call: _e.mock.On("SessionPaths", ctx, sessionNames)}
}

func (_c *MockQueryPort_SessionPaths_Call) Run(run func(ctx context.Context, sessionNames []string)) *MockQueryPort_SessionPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryPort_SessionPaths_Call) Return(stringToString map[string]string, err error) *MockQueryPort_SessionPaths_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockQueryPort_SessionPaths_Call) RunAndReturn(run func(ctx context.Context, sessionNames []string) (map[string]string, error)) *MockQueryPort_SessionPaths_Call {
	_c.Call.Return(run)
	return _c
}
