// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPCClientPort creates a new instance of MockIPCClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPCClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPCClientPort {
	mock := &MockIPCClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPCClientPort is an autogenerated mock type for the IPCClientPort type
type MockIPCClientPort struct {
	mock.Mock
}

type MockIPCClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPCClientPort) EXPECT() *MockIPCClientPort_Expecter {
	return &MockIPCClientPort_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockIPCClientPort
func (_mock *MockIPCClientPort) Send(ctx context.Context, req ports.Request) (ports.Response, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 ports.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.Request) (ports.Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.Request) ports.Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(ports.Response)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCClientPort_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockIPCClientPort_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - req ports.Request
func (_e *MockIPCClientPort_Expecter) Send(ctx any, req any) *MockIPCClientPort_Send_Call {
	return &MockIPCClientPort_Send_Call{Call: _e.mock.On("Send", ctx, req)}
}

func (_c *MockIPCClientPort_Send_Call) Run(run func(ctx context.Context, req ports.Request)) *MockIPCClientPort_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.Request
		if args[1] != nil {
			arg1 = args[1].(ports.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPCClientPort_Send_Call) Return(response ports.Response, err error) *MockIPCClientPort_Send_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockIPCClientPort_Send_Call) RunAndReturn(run func(ctx context.Context, req ports.Request) (ports.Response, error)) *MockIPCClientPort_Send_Call {
	_c.Call.Return(run)
	return _c
}
