// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSidebarPort creates a new instance of MockSidebarPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSidebarPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSidebarPort {
	mock := &MockSidebarPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSidebarPort is an autogenerated mock type for the SidebarPort type
type MockSidebarPort struct {
	mock.Mock
}

type MockSidebarPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSidebarPort) EXPECT() *MockSidebarPort_Expecter {
	return &MockSidebarPort_Expecter{mock: &_m.Mock}
}

// AttachSingletonSidebar provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) AttachSingletonSidebar(ctx context.Context, clientID string, paneID string, width string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, clientID, paneID, width)

	if len(ret) == 0 {
		panic("no return value specified for AttachSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, clientID, paneID, width)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, clientID, paneID, width)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, clientID, paneID, width)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSidebarPort_AttachSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachSingletonSidebar'
type MockSidebarPort_AttachSingletonSidebar_Call struct {
	*mock.Call
}

// AttachSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - paneID string
//   - width string
func (_e *MockSidebarPort_Expecter) AttachSingletonSidebar(ctx any, clientID any, paneID any, width any) *MockSidebarPort_AttachSingletonSidebar_Call {
	return &MockSidebarPort_AttachSingletonSidebar_Call{Call: _e.mock.On("AttachSingletonSidebar", ctx, clientID, paneID, width)}
}

func (_c *MockSidebarPort_AttachSingletonSidebar_Call) Run(run func(ctx context.Context, clientID string, paneID string, width string)) *MockSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSidebarPort_AttachSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockSidebarPort_AttachSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string, paneID string, width string) (ports.PaneRef, error)) *MockSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// CloseAfterSwitch provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) CloseAfterSwitch(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CloseAfterSwitch")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSidebarPort_CloseAfterSwitch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAfterSwitch'
type MockSidebarPort_CloseAfterSwitch_Call struct {
	*mock.Call
}

// CloseAfterSwitch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSidebarPort_Expecter) CloseAfterSwitch(ctx any) *MockSidebarPort_CloseAfterSwitch_Call {
	return &MockSidebarPort_CloseAfterSwitch_Call{Call: _e.mock.On("CloseAfterSwitch", ctx)}
}

func (_c *MockSidebarPort_CloseAfterSwitch_Call) Run(run func(ctx context.Context)) *MockSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSidebarPort_CloseAfterSwitch_Call) Return(b bool, err error) *MockSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSidebarPort_CloseAfterSwitch_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSingletonSidebar provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) EnsureSingletonSidebar(ctx context.Context, command []string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSidebarPort_EnsureSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSingletonSidebar'
type MockSidebarPort_EnsureSingletonSidebar_Call struct {
	*mock.Call
}

// EnsureSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - command []string
func (_e *MockSidebarPort_Expecter) EnsureSingletonSidebar(ctx any, command any) *MockSidebarPort_EnsureSingletonSidebar_Call {
	return &MockSidebarPort_EnsureSingletonSidebar_Call{Call: _e.mock.On("EnsureSingletonSidebar", ctx, command)}
}

func (_c *MockSidebarPort_EnsureSingletonSidebar_Call) Run(run func(ctx context.Context, command []string)) *MockSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSidebarPort_EnsureSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockSidebarPort_EnsureSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, command []string) (ports.PaneRef, error)) *MockSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// FindSidebarPane provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) FindSidebarPane(ctx context.Context, target string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for FindSidebarPane")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSidebarPort_FindSidebarPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSidebarPane'
type MockSidebarPort_FindSidebarPane_Call struct {
	*mock.Call
}

// FindSidebarPane is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockSidebarPort_Expecter) FindSidebarPane(ctx any, target any) *MockSidebarPort_FindSidebarPane_Call {
	return &MockSidebarPort_FindSidebarPane_Call{Call: _e.mock.On("FindSidebarPane", ctx, target)}
}

func (_c *MockSidebarPort_FindSidebarPane_Call) Run(run func(ctx context.Context, target string)) *MockSidebarPort_FindSidebarPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSidebarPort_FindSidebarPane_Call) Return(paneRef ports.PaneRef, err error) *MockSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockSidebarPort_FindSidebarPane_Call) RunAndReturn(run func(ctx context.Context, target string) (ports.PaneRef, error)) *MockSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(run)
	return _c
}

// FindSingletonSidebar provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) FindSingletonSidebar(ctx context.Context) (ports.PaneRef, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.PaneRef, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.PaneRef); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSidebarPort_FindSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSingletonSidebar'
type MockSidebarPort_FindSingletonSidebar_Call struct {
	*mock.Call
}

// FindSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSidebarPort_Expecter) FindSingletonSidebar(ctx any) *MockSidebarPort_FindSingletonSidebar_Call {
	return &MockSidebarPort_FindSingletonSidebar_Call{Call: _e.mock.On("FindSingletonSidebar", ctx)}
}

func (_c *MockSidebarPort_FindSingletonSidebar_Call) Run(run func(ctx context.Context)) *MockSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSidebarPort_FindSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockSidebarPort_FindSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context) (ports.PaneRef, error)) *MockSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// ParkSingletonSidebar provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) ParkSingletonSidebar(ctx context.Context, paneID string) error {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ParkSingletonSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSidebarPort_ParkSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParkSingletonSidebar'
type MockSidebarPort_ParkSingletonSidebar_Call struct {
	*mock.Call
}

// ParkSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockSidebarPort_Expecter) ParkSingletonSidebar(ctx any, paneID any) *MockSidebarPort_ParkSingletonSidebar_Call {
	return &MockSidebarPort_ParkSingletonSidebar_Call{Call: _e.mock.On("ParkSingletonSidebar", ctx, paneID)}
}

func (_c *MockSidebarPort_ParkSingletonSidebar_Call) Run(run func(ctx context.Context, paneID string)) *MockSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSidebarPort_ParkSingletonSidebar_Call) Return(err error) *MockSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSidebarPort_ParkSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, paneID string) error) *MockSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSidebar provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) RefreshSidebar(ctx context.Context, clientID string) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSidebarPort_RefreshSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSidebar'
type MockSidebarPort_RefreshSidebar_Call struct {
	*mock.Call
}

// RefreshSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockSidebarPort_Expecter) RefreshSidebar(ctx any, clientID any) *MockSidebarPort_RefreshSidebar_Call {
	return &MockSidebarPort_RefreshSidebar_Call{Call: _e.mock.On("RefreshSidebar", ctx, clientID)}
}

func (_c *MockSidebarPort_RefreshSidebar_Call) Run(run func(ctx context.Context, clientID string)) *MockSidebarPort_RefreshSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSidebarPort_RefreshSidebar_Call) Return(err error) *MockSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSidebarPort_RefreshSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string) error) *MockSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleSidebarRestoreOnExit provides a mock function for the type MockSidebarPort
func (_mock *MockSidebarPort) ScheduleSidebarRestoreOnExit(ctx context.Context, clientID string, paneID string) error {
	ret := _mock.Called(ctx, clientID, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleSidebarRestoreOnExit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSidebarPort_ScheduleSidebarRestoreOnExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleSidebarRestoreOnExit'
type MockSidebarPort_ScheduleSidebarRestoreOnExit_Call struct {
	*mock.Call
}

// ScheduleSidebarRestoreOnExit is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - paneID string
func (_e *MockSidebarPort_Expecter) ScheduleSidebarRestoreOnExit(ctx any, clientID any, paneID any) *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	return &MockSidebarPort_ScheduleSidebarRestoreOnExit_Call{Call: _e.mock.On("ScheduleSidebarRestoreOnExit", ctx, clientID, paneID)}
}

func (_c *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call) Run(run func(ctx context.Context, clientID string, paneID string)) *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call) Return(err error) *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call) RunAndReturn(run func(ctx context.Context, clientID string, paneID string) error) *MockSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(run)
	return _c
}
