// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDaemonLauncherPort creates a new instance of MockDaemonLauncherPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDaemonLauncherPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDaemonLauncherPort {
	mock := &MockDaemonLauncherPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDaemonLauncherPort is an autogenerated mock type for the DaemonLauncherPort type
type MockDaemonLauncherPort struct {
	mock.Mock
}

type MockDaemonLauncherPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDaemonLauncherPort) EXPECT() *MockDaemonLauncherPort_Expecter {
	return &MockDaemonLauncherPort_Expecter{mock: &_m.Mock}
}

// EnsureStarted provides a mock function for the type MockDaemonLauncherPort
func (_mock *MockDaemonLauncherPort) EnsureStarted(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureStarted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDaemonLauncherPort_EnsureStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureStarted'
type MockDaemonLauncherPort_EnsureStarted_Call struct {
	*mock.Call
}

// EnsureStarted is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDaemonLauncherPort_Expecter) EnsureStarted(ctx any) *MockDaemonLauncherPort_EnsureStarted_Call {
	return &MockDaemonLauncherPort_EnsureStarted_Call{Call: _e.mock.On("EnsureStarted", ctx)}
}

func (_c *MockDaemonLauncherPort_EnsureStarted_Call) Run(run func(ctx context.Context)) *MockDaemonLauncherPort_EnsureStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDaemonLauncherPort_EnsureStarted_Call) Return(err error) *MockDaemonLauncherPort_EnsureStarted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDaemonLauncherPort_EnsureStarted_Call) RunAndReturn(run func(ctx context.Context) error) *MockDaemonLauncherPort_EnsureStarted_Call {
	_c.Call.Return(run)
	return _c
}
