// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateStorePort creates a new instance of MockStateStorePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStorePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateStorePort {
	mock := &MockStateStorePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateStorePort is an autogenerated mock type for the StateStorePort type
type MockStateStorePort struct {
	mock.Mock
}

type MockStateStorePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateStorePort) EXPECT() *MockStateStorePort_Expecter {
	return &MockStateStorePort_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockStateStorePort
func (_mock *MockStateStorePort) Load(ctx context.Context, serverID string) (ports.PersistedState, error) {
	ret := _mock.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 ports.PersistedState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PersistedState, error)); ok {
		return returnFunc(ctx, serverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PersistedState); ok {
		r0 = returnFunc(ctx, serverID)
	} else {
		r0 = ret.Get(0).(ports.PersistedState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateStorePort_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStateStorePort_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockStateStorePort_Expecter) Load(ctx any, serverID any) *MockStateStorePort_Load_Call {
	return &MockStateStorePort_Load_Call{Call: _e.mock.On("Load", ctx, serverID)}
}

func (_c *MockStateStorePort_Load_Call) Run(run func(ctx context.Context, serverID string)) *MockStateStorePort_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStorePort_Load_Call) Return(persistedState ports.PersistedState, err error) *MockStateStorePort_Load_Call {
	_c.Call.Return(persistedState, err)
	return _c
}

func (_c *MockStateStorePort_Load_Call) RunAndReturn(run func(ctx context.Context, serverID string) (ports.PersistedState, error)) *MockStateStorePort_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStateStorePort
func (_mock *MockStateStorePort) Save(ctx context.Context, serverID string, state ports.PersistedState) error {
	ret := _mock.Called(ctx, serverID, state)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.PersistedState) error); ok {
		r0 = returnFunc(ctx, serverID, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStorePort_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStateStorePort_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - state ports.PersistedState
func (_e *MockStateStorePort_Expecter) Save(ctx any, serverID any, state any) *MockStateStorePort_Save_Call {
	return &MockStateStorePort_Save_Call{Call: _e.mock.On("Save", ctx, serverID, state)}
}

func (_c *MockStateStorePort_Save_Call) Run(run func(ctx context.Context, serverID string, state ports.PersistedState)) *MockStateStorePort_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ports.PersistedState
		if args[2] != nil {
			arg2 = args[2].(ports.PersistedState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStateStorePort_Save_Call) Return(err error) *MockStateStorePort_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStorePort_Save_Call) RunAndReturn(run func(ctx context.Context, serverID string, state ports.PersistedState) error) *MockStateStorePort_Save_Call {
	_c.Call.Return(run)
	return _c
}
