// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerPort creates a new instance of MockLoggerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerPort {
	mock := &MockLoggerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerPort is an autogenerated mock type for the LoggerPort type
type MockLoggerPort struct {
	mock.Mock
}

type MockLoggerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerPort) EXPECT() *MockLoggerPort_Expecter {
	return &MockLoggerPort_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLoggerPort
func (_mock *MockLoggerPort) Debug(msg string, fields []ports.LogField) {
	_mock.Called(msg, fields)
	return
}

// MockLoggerPort_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLoggerPort_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - fields []ports.LogField
func (_e *MockLoggerPort_Expecter) Debug(msg any, fields any) *MockLoggerPort_Debug_Call {
	return &MockLoggerPort_Debug_Call{Call: _e.mock.On("Debug", msg, fields)}
}

func (_c *MockLoggerPort_Debug_Call) Run(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []ports.LogField
		if args[1] != nil {
			arg1 = args[1].([]ports.LogField)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerPort_Debug_Call) Return() *MockLoggerPort_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerPort_Debug_Call) RunAndReturn(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLoggerPort
func (_mock *MockLoggerPort) Error(msg string, fields []ports.LogField) {
	_mock.Called(msg, fields)
	return
}

// MockLoggerPort_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLoggerPort_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields []ports.LogField
func (_e *MockLoggerPort_Expecter) Error(msg any, fields any) *MockLoggerPort_Error_Call {
	return &MockLoggerPort_Error_Call{Call: _e.mock.On("Error", msg, fields)}
}

func (_c *MockLoggerPort_Error_Call) Run(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []ports.LogField
		if args[1] != nil {
			arg1 = args[1].([]ports.LogField)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerPort_Error_Call) Return() *MockLoggerPort_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerPort_Error_Call) RunAndReturn(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLoggerPort
func (_mock *MockLoggerPort) Info(msg string, fields []ports.LogField) {
	_mock.Called(msg, fields)
	return
}

// MockLoggerPort_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLoggerPort_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields []ports.LogField
func (_e *MockLoggerPort_Expecter) Info(msg any, fields any) *MockLoggerPort_Info_Call {
	return &MockLoggerPort_Info_Call{Call: _e.mock.On("Info", msg, fields)}
}

func (_c *MockLoggerPort_Info_Call) Run(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []ports.LogField
		if args[1] != nil {
			arg1 = args[1].([]ports.LogField)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoggerPort_Info_Call) Return() *MockLoggerPort_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerPort_Info_Call) RunAndReturn(run func(msg string, fields []ports.LogField)) *MockLoggerPort_Info_Call {
	_c.Run(run)
	return _c
}
