// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitPort creates a new instance of MockGitPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitPort {
	mock := &MockGitPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitPort is an autogenerated mock type for the GitPort type
type MockGitPort struct {
	mock.Mock
}

type MockGitPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitPort) EXPECT() *MockGitPort_Expecter {
	return &MockGitPort_Expecter{mock: &_m.Mock}
}

// RepoInfo provides a mock function for the type MockGitPort
func (_mock *MockGitPort) RepoInfo(ctx context.Context, path string) (ports.GitRepoInfo, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for RepoInfo")
	}

	var r0 ports.GitRepoInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.GitRepoInfo, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.GitRepoInfo); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(ports.GitRepoInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitPort_RepoInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoInfo'
type MockGitPort_RepoInfo_Call struct {
	*mock.Call
}

// RepoInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitPort_Expecter) RepoInfo(ctx interface{}, path interface{}) *MockGitPort_RepoInfo_Call {
	return &MockGitPort_RepoInfo_Call{Call: _e.mock.On("RepoInfo", ctx, path)}
}

func (_c *MockGitPort_RepoInfo_Call) Run(run func(ctx context.Context, path string)) *MockGitPort_RepoInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitPort_RepoInfo_Call) Return(gitRepoInfo ports.GitRepoInfo, err error) *MockGitPort_RepoInfo_Call {
	_c.Call.Return(gitRepoInfo, err)
	return _c
}

func (_c *MockGitPort_RepoInfo_Call) RunAndReturn(run func(ctx context.Context, path string) (ports.GitRepoInfo, error)) *MockGitPort_RepoInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RepoRoot provides a mock function for the type MockGitPort
func (_mock *MockGitPort) RepoRoot(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for RepoRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitPort_RepoRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoRoot'
type MockGitPort_RepoRoot_Call struct {
	*mock.Call
}

// RepoRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitPort_Expecter) RepoRoot(ctx interface{}, path interface{}) *MockGitPort_RepoRoot_Call {
	return &MockGitPort_RepoRoot_Call{Call: _e.mock.On("RepoRoot", ctx, path)}
}

func (_c *MockGitPort_RepoRoot_Call) Run(run func(ctx context.Context, path string)) *MockGitPort_RepoRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitPort_RepoRoot_Call) Return(s string, err error) *MockGitPort_RepoRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitPort_RepoRoot_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *MockGitPort_RepoRoot_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockGitPort
func (_mock *MockGitPort) Status(ctx context.Context, path string) (ports.GitStatus, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 ports.GitStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.GitStatus, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.GitStatus); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(ports.GitStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitPort_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockGitPort_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitPort_Expecter) Status(ctx interface{}, path interface{}) *MockGitPort_Status_Call {
	return &MockGitPort_Status_Call{Call: _e.mock.On("Status", ctx, path)}
}

func (_c *MockGitPort_Status_Call) Run(run func(ctx context.Context, path string)) *MockGitPort_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitPort_Status_Call) Return(gitStatus ports.GitStatus, err error) *MockGitPort_Status_Call {
	_c.Call.Return(gitStatus, err)
	return _c
}

func (_c *MockGitPort_Status_Call) RunAndReturn(run func(ctx context.Context, path string) (ports.GitStatus, error)) *MockGitPort_Status_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTargets provides a mock function for the type MockGitPort
func (_mock *MockGitPort) WatchTargets(ctx context.Context, path string) (ports.GitWatchTargets, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for WatchTargets")
	}

	var r0 ports.GitWatchTargets
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.GitWatchTargets, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.GitWatchTargets); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(ports.GitWatchTargets)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitPort_WatchTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTargets'
type MockGitPort_WatchTargets_Call struct {
	*mock.Call
}

// WatchTargets is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitPort_Expecter) WatchTargets(ctx interface{}, path interface{}) *MockGitPort_WatchTargets_Call {
	return &MockGitPort_WatchTargets_Call{Call: _e.mock.On("WatchTargets", ctx, path)}
}

func (_c *MockGitPort_WatchTargets_Call) Run(run func(ctx context.Context, path string)) *MockGitPort_WatchTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitPort_WatchTargets_Call) Return(gitWatchTargets ports.GitWatchTargets, err error) *MockGitPort_WatchTargets_Call {
	_c.Call.Return(gitWatchTargets, err)
	return _c
}

func (_c *MockGitPort_WatchTargets_Call) RunAndReturn(run func(ctx context.Context, path string) (ports.GitWatchTargets, error)) *MockGitPort_WatchTargets_Call {
	_c.Call.Return(run)
	return _c
}
