// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileWatcherPort creates a new instance of MockFileWatcherPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileWatcherPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileWatcherPort {
	mock := &MockFileWatcherPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileWatcherPort is an autogenerated mock type for the FileWatcherPort type
type MockFileWatcherPort struct {
	mock.Mock
}

type MockFileWatcherPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileWatcherPort) EXPECT() *MockFileWatcherPort_Expecter {
	return &MockFileWatcherPort_Expecter{mock: &_m.Mock}
}

// Watch provides a mock function for the type MockFileWatcherPort
func (_mock *MockFileWatcherPort) Watch(ctx context.Context, paths []string) (<-chan ports.FileWatchEvent, <-chan error, error) {
	ret := _mock.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan ports.FileWatchEvent
	var r1 <-chan error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (<-chan ports.FileWatchEvent, <-chan error, error)); ok {
		return returnFunc(ctx, paths)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) <-chan ports.FileWatchEvent); ok {
		r0 = returnFunc(ctx, paths)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ports.FileWatchEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) <-chan error); ok {
		r1 = returnFunc(ctx, paths)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = returnFunc(ctx, paths)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFileWatcherPort_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockFileWatcherPort_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *MockFileWatcherPort_Expecter) Watch(ctx interface{}, paths interface{}) *MockFileWatcherPort_Watch_Call {
	return &MockFileWatcherPort_Watch_Call{Call: _e.mock.On("Watch", ctx, paths)}
}

func (_c *MockFileWatcherPort_Watch_Call) Run(run func(ctx context.Context, paths []string)) *MockFileWatcherPort_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileWatcherPort_Watch_Call) Return(fileWatchEventCh <-chan ports.FileWatchEvent, errCh <-chan error, err error) *MockFileWatcherPort_Watch_Call {
	_c.Call.Return(fileWatchEventCh, errCh, err)
	return _c
}

func (_c *MockFileWatcherPort_Watch_Call) RunAndReturn(run func(ctx context.Context, paths []string) (<-chan ports.FileWatchEvent, <-chan error, error)) *MockFileWatcherPort_Watch_Call {
	_c.Call.Return(run)
	return _c
}
