// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxSidebarPort creates a new instance of MockTmuxSidebarPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxSidebarPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxSidebarPort {
	mock := &MockTmuxSidebarPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxSidebarPort is an autogenerated mock type for the TmuxSidebarPort type
type MockTmuxSidebarPort struct {
	mock.Mock
}

type MockTmuxSidebarPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxSidebarPort) EXPECT() *MockTmuxSidebarPort_Expecter {
	return &MockTmuxSidebarPort_Expecter{mock: &_m.Mock}
}

// CloseAfterSwitch provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) CloseAfterSwitch(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CloseAfterSwitch")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_CloseAfterSwitch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAfterSwitch'
type MockTmuxSidebarPort_CloseAfterSwitch_Call struct {
	*mock.Call
}

// CloseAfterSwitch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxSidebarPort_Expecter) CloseAfterSwitch(ctx interface{}) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	return &MockTmuxSidebarPort_CloseAfterSwitch_Call{Call: _e.mock.On("CloseAfterSwitch", ctx)}
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) Run(run func(ctx context.Context)) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) Return(b bool, err error) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(run)
	return _c
}

// CloseSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) CloseSidebar(ctx context.Context, clientID string) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CloseSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_CloseSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSidebar'
type MockTmuxSidebarPort_CloseSidebar_Call struct {
	*mock.Call
}

// CloseSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTmuxSidebarPort_Expecter) CloseSidebar(ctx interface{}, clientID interface{}) *MockTmuxSidebarPort_CloseSidebar_Call {
	return &MockTmuxSidebarPort_CloseSidebar_Call{Call: _e.mock.On("CloseSidebar", ctx, clientID)}
}

func (_c *MockTmuxSidebarPort_CloseSidebar_Call) Run(run func(ctx context.Context, clientID string)) *MockTmuxSidebarPort_CloseSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_CloseSidebar_Call) Return(err error) *MockTmuxSidebarPort_CloseSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_CloseSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string) error) *MockTmuxSidebarPort_CloseSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// CloseSidebarPane provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) CloseSidebarPane(ctx context.Context, paneID string) error {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for CloseSidebarPane")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_CloseSidebarPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSidebarPane'
type MockTmuxSidebarPort_CloseSidebarPane_Call struct {
	*mock.Call
}

// CloseSidebarPane is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockTmuxSidebarPort_Expecter) CloseSidebarPane(ctx interface{}, paneID interface{}) *MockTmuxSidebarPort_CloseSidebarPane_Call {
	return &MockTmuxSidebarPort_CloseSidebarPane_Call{Call: _e.mock.On("CloseSidebarPane", ctx, paneID)}
}

func (_c *MockTmuxSidebarPort_CloseSidebarPane_Call) Run(run func(ctx context.Context, paneID string)) *MockTmuxSidebarPort_CloseSidebarPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_CloseSidebarPane_Call) Return(err error) *MockTmuxSidebarPort_CloseSidebarPane_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_CloseSidebarPane_Call) RunAndReturn(run func(ctx context.Context, paneID string) error) *MockTmuxSidebarPort_CloseSidebarPane_Call {
	_c.Call.Return(run)
	return _c
}

// FindSidebarPane provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) FindSidebarPane(ctx context.Context, target string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for FindSidebarPane")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_FindSidebarPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSidebarPane'
type MockTmuxSidebarPort_FindSidebarPane_Call struct {
	*mock.Call
}

// FindSidebarPane is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockTmuxSidebarPort_Expecter) FindSidebarPane(ctx interface{}, target interface{}) *MockTmuxSidebarPort_FindSidebarPane_Call {
	return &MockTmuxSidebarPort_FindSidebarPane_Call{Call: _e.mock.On("FindSidebarPane", ctx, target)}
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) Run(run func(ctx context.Context, target string)) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) RunAndReturn(run func(ctx context.Context, target string) (ports.PaneRef, error)) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) OpenSidebar(ctx context.Context, clientID string, command []string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, clientID, command)

	if len(ret) == 0 {
		panic("no return value specified for OpenSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, clientID, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, clientID, command)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, clientID, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_OpenSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSidebar'
type MockTmuxSidebarPort_OpenSidebar_Call struct {
	*mock.Call
}

// OpenSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - command []string
func (_e *MockTmuxSidebarPort_Expecter) OpenSidebar(ctx interface{}, clientID interface{}, command interface{}) *MockTmuxSidebarPort_OpenSidebar_Call {
	return &MockTmuxSidebarPort_OpenSidebar_Call{Call: _e.mock.On("OpenSidebar", ctx, clientID, command)}
}

func (_c *MockTmuxSidebarPort_OpenSidebar_Call) Run(run func(ctx context.Context, clientID string, command []string)) *MockTmuxSidebarPort_OpenSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_OpenSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_OpenSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_OpenSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string, command []string) (ports.PaneRef, error)) *MockTmuxSidebarPort_OpenSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) RefreshSidebar(ctx context.Context, clientID string) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_RefreshSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSidebar'
type MockTmuxSidebarPort_RefreshSidebar_Call struct {
	*mock.Call
}

// RefreshSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTmuxSidebarPort_Expecter) RefreshSidebar(ctx interface{}, clientID interface{}) *MockTmuxSidebarPort_RefreshSidebar_Call {
	return &MockTmuxSidebarPort_RefreshSidebar_Call{Call: _e.mock.On("RefreshSidebar", ctx, clientID)}
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) Run(run func(ctx context.Context, clientID string)) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) Return(err error) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string) error) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleSidebarRestoreOnExit provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) ScheduleSidebarRestoreOnExit(ctx context.Context, clientID string, paneID string) error {
	ret := _mock.Called(ctx, clientID, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleSidebarRestoreOnExit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleSidebarRestoreOnExit'
type MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call struct {
	*mock.Call
}

// ScheduleSidebarRestoreOnExit is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - paneID string
func (_e *MockTmuxSidebarPort_Expecter) ScheduleSidebarRestoreOnExit(ctx interface{}, clientID interface{}, paneID interface{}) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	return &MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call{Call: _e.mock.On("ScheduleSidebarRestoreOnExit", ctx, clientID, paneID)}
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) Run(run func(ctx context.Context, clientID string, paneID string)) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) Return(err error) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) RunAndReturn(run func(ctx context.Context, clientID string, paneID string) error) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(run)
	return _c
}
