// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxSidebarPort creates a new instance of MockTmuxSidebarPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxSidebarPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxSidebarPort {
	mock := &MockTmuxSidebarPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxSidebarPort is an autogenerated mock type for the TmuxSidebarPort type
type MockTmuxSidebarPort struct {
	mock.Mock
}

type MockTmuxSidebarPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxSidebarPort) EXPECT() *MockTmuxSidebarPort_Expecter {
	return &MockTmuxSidebarPort_Expecter{mock: &_m.Mock}
}

// AttachSingletonSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) AttachSingletonSidebar(ctx context.Context, clientID string, paneID string, width string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, clientID, paneID, width)

	if len(ret) == 0 {
		panic("no return value specified for AttachSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, clientID, paneID, width)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, clientID, paneID, width)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, clientID, paneID, width)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_AttachSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachSingletonSidebar'
type MockTmuxSidebarPort_AttachSingletonSidebar_Call struct {
	*mock.Call
}

// AttachSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - paneID string
//   - width string
func (_e *MockTmuxSidebarPort_Expecter) AttachSingletonSidebar(ctx interface{}, clientID interface{}, paneID interface{}, width interface{}) *MockTmuxSidebarPort_AttachSingletonSidebar_Call {
	return &MockTmuxSidebarPort_AttachSingletonSidebar_Call{Call: _e.mock.On("AttachSingletonSidebar", ctx, clientID, paneID, width)}
}

func (_c *MockTmuxSidebarPort_AttachSingletonSidebar_Call) Run(run func(ctx context.Context, clientID string, paneID string, width string)) *MockTmuxSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_AttachSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_AttachSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string, paneID string, width string) (ports.PaneRef, error)) *MockTmuxSidebarPort_AttachSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// CloseAfterSwitch provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) CloseAfterSwitch(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CloseAfterSwitch")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_CloseAfterSwitch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAfterSwitch'
type MockTmuxSidebarPort_CloseAfterSwitch_Call struct {
	*mock.Call
}

// CloseAfterSwitch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxSidebarPort_Expecter) CloseAfterSwitch(ctx interface{}) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	return &MockTmuxSidebarPort_CloseAfterSwitch_Call{Call: _e.mock.On("CloseAfterSwitch", ctx)}
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) Run(run func(ctx context.Context)) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) Return(b bool, err error) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTmuxSidebarPort_CloseAfterSwitch_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockTmuxSidebarPort_CloseAfterSwitch_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSingletonSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) EnsureSingletonSidebar(ctx context.Context, command []string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_EnsureSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSingletonSidebar'
type MockTmuxSidebarPort_EnsureSingletonSidebar_Call struct {
	*mock.Call
}

// EnsureSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - command []string
func (_e *MockTmuxSidebarPort_Expecter) EnsureSingletonSidebar(ctx interface{}, command interface{}) *MockTmuxSidebarPort_EnsureSingletonSidebar_Call {
	return &MockTmuxSidebarPort_EnsureSingletonSidebar_Call{Call: _e.mock.On("EnsureSingletonSidebar", ctx, command)}
}

func (_c *MockTmuxSidebarPort_EnsureSingletonSidebar_Call) Run(run func(ctx context.Context, command []string)) *MockTmuxSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_EnsureSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_EnsureSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, command []string) (ports.PaneRef, error)) *MockTmuxSidebarPort_EnsureSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// FindSidebarPane provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) FindSidebarPane(ctx context.Context, target string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for FindSidebarPane")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_FindSidebarPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSidebarPane'
type MockTmuxSidebarPort_FindSidebarPane_Call struct {
	*mock.Call
}

// FindSidebarPane is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockTmuxSidebarPort_Expecter) FindSidebarPane(ctx interface{}, target interface{}) *MockTmuxSidebarPort_FindSidebarPane_Call {
	return &MockTmuxSidebarPort_FindSidebarPane_Call{Call: _e.mock.On("FindSidebarPane", ctx, target)}
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) Run(run func(ctx context.Context, target string)) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_FindSidebarPane_Call) RunAndReturn(run func(ctx context.Context, target string) (ports.PaneRef, error)) *MockTmuxSidebarPort_FindSidebarPane_Call {
	_c.Call.Return(run)
	return _c
}

// FindSingletonSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) FindSingletonSidebar(ctx context.Context) (ports.PaneRef, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindSingletonSidebar")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.PaneRef, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.PaneRef); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxSidebarPort_FindSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSingletonSidebar'
type MockTmuxSidebarPort_FindSingletonSidebar_Call struct {
	*mock.Call
}

// FindSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxSidebarPort_Expecter) FindSingletonSidebar(ctx interface{}) *MockTmuxSidebarPort_FindSingletonSidebar_Call {
	return &MockTmuxSidebarPort_FindSingletonSidebar_Call{Call: _e.mock.On("FindSingletonSidebar", ctx)}
}

func (_c *MockTmuxSidebarPort_FindSingletonSidebar_Call) Run(run func(ctx context.Context)) *MockTmuxSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_FindSingletonSidebar_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxSidebarPort_FindSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context) (ports.PaneRef, error)) *MockTmuxSidebarPort_FindSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// ParkSingletonSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) ParkSingletonSidebar(ctx context.Context, paneID string) error {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ParkSingletonSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_ParkSingletonSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParkSingletonSidebar'
type MockTmuxSidebarPort_ParkSingletonSidebar_Call struct {
	*mock.Call
}

// ParkSingletonSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockTmuxSidebarPort_Expecter) ParkSingletonSidebar(ctx interface{}, paneID interface{}) *MockTmuxSidebarPort_ParkSingletonSidebar_Call {
	return &MockTmuxSidebarPort_ParkSingletonSidebar_Call{Call: _e.mock.On("ParkSingletonSidebar", ctx, paneID)}
}

func (_c *MockTmuxSidebarPort_ParkSingletonSidebar_Call) Run(run func(ctx context.Context, paneID string)) *MockTmuxSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_ParkSingletonSidebar_Call) Return(err error) *MockTmuxSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_ParkSingletonSidebar_Call) RunAndReturn(run func(ctx context.Context, paneID string) error) *MockTmuxSidebarPort_ParkSingletonSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSidebar provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) RefreshSidebar(ctx context.Context, clientID string) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSidebar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_RefreshSidebar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSidebar'
type MockTmuxSidebarPort_RefreshSidebar_Call struct {
	*mock.Call
}

// RefreshSidebar is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTmuxSidebarPort_Expecter) RefreshSidebar(ctx interface{}, clientID interface{}) *MockTmuxSidebarPort_RefreshSidebar_Call {
	return &MockTmuxSidebarPort_RefreshSidebar_Call{Call: _e.mock.On("RefreshSidebar", ctx, clientID)}
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) Run(run func(ctx context.Context, clientID string)) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) Return(err error) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_RefreshSidebar_Call) RunAndReturn(run func(ctx context.Context, clientID string) error) *MockTmuxSidebarPort_RefreshSidebar_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleSidebarRestoreOnExit provides a mock function for the type MockTmuxSidebarPort
func (_mock *MockTmuxSidebarPort) ScheduleSidebarRestoreOnExit(ctx context.Context, clientID string, paneID string) error {
	ret := _mock.Called(ctx, clientID, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleSidebarRestoreOnExit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleSidebarRestoreOnExit'
type MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call struct {
	*mock.Call
}

// ScheduleSidebarRestoreOnExit is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - paneID string
func (_e *MockTmuxSidebarPort_Expecter) ScheduleSidebarRestoreOnExit(ctx interface{}, clientID interface{}, paneID interface{}) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	return &MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call{Call: _e.mock.On("ScheduleSidebarRestoreOnExit", ctx, clientID, paneID)}
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) Run(run func(ctx context.Context, clientID string, paneID string)) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) Return(err error) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call) RunAndReturn(run func(ctx context.Context, clientID string, paneID string) error) *MockTmuxSidebarPort_ScheduleSidebarRestoreOnExit_Call {
	_c.Call.Return(run)
	return _c
}
