// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPCServerPort creates a new instance of MockIPCServerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPCServerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPCServerPort {
	mock := &MockIPCServerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPCServerPort is an autogenerated mock type for the IPCServerPort type
type MockIPCServerPort struct {
	mock.Mock
}

type MockIPCServerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPCServerPort) EXPECT() *MockIPCServerPort_Expecter {
	return &MockIPCServerPort_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function for the type MockIPCServerPort
func (_mock *MockIPCServerPort) Serve(ctx context.Context, handler ports.IPCHandler) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.IPCHandler) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPCServerPort_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockIPCServerPort_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - ctx context.Context
//   - handler ports.IPCHandler
func (_e *MockIPCServerPort_Expecter) Serve(ctx interface{}, handler interface{}) *MockIPCServerPort_Serve_Call {
	return &MockIPCServerPort_Serve_Call{Call: _e.mock.On("Serve", ctx, handler)}
}

func (_c *MockIPCServerPort_Serve_Call) Run(run func(ctx context.Context, handler ports.IPCHandler)) *MockIPCServerPort_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.IPCHandler
		if args[1] != nil {
			arg1 = args[1].(ports.IPCHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPCServerPort_Serve_Call) Return(err error) *MockIPCServerPort_Serve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPCServerPort_Serve_Call) RunAndReturn(run func(ctx context.Context, handler ports.IPCHandler) error) *MockIPCServerPort_Serve_Call {
	_c.Call.Return(run)
	return _c
}
