// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxControlPort creates a new instance of MockTmuxControlPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxControlPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxControlPort {
	mock := &MockTmuxControlPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxControlPort is an autogenerated mock type for the TmuxControlPort type
type MockTmuxControlPort struct {
	mock.Mock
}

type MockTmuxControlPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxControlPort) EXPECT() *MockTmuxControlPort_Expecter {
	return &MockTmuxControlPort_Expecter{mock: &_m.Mock}
}

// ClosePane provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) ClosePane(ctx context.Context, paneID string) error {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for ClosePane")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_ClosePane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePane'
type MockTmuxControlPort_ClosePane_Call struct {
	*mock.Call
}

// ClosePane is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockTmuxControlPort_Expecter) ClosePane(ctx interface{}, paneID interface{}) *MockTmuxControlPort_ClosePane_Call {
	return &MockTmuxControlPort_ClosePane_Call{Call: _e.mock.On("ClosePane", ctx, paneID)}
}

func (_c *MockTmuxControlPort_ClosePane_Call) Run(run func(ctx context.Context, paneID string)) *MockTmuxControlPort_ClosePane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_ClosePane_Call) Return(err error) *MockTmuxControlPort_ClosePane_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_ClosePane_Call) RunAndReturn(run func(ctx context.Context, paneID string) error) *MockTmuxControlPort_ClosePane_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) CreateSession(ctx context.Context, sessionName string, path string) error {
	ret := _mock.Called(ctx, sessionName, path)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sessionName, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTmuxControlPort_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - path string
func (_e *MockTmuxControlPort_Expecter) CreateSession(ctx interface{}, sessionName interface{}, path interface{}) *MockTmuxControlPort_CreateSession_Call {
	return &MockTmuxControlPort_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, sessionName, path)}
}

func (_c *MockTmuxControlPort_CreateSession_Call) Run(run func(ctx context.Context, sessionName string, path string)) *MockTmuxControlPort_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_CreateSession_Call) Return(err error) *MockTmuxControlPort_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_CreateSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string, path string) error) *MockTmuxControlPort_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayMessage provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) DisplayMessage(ctx context.Context, clientID string, message string) error {
	ret := _mock.Called(ctx, clientID, message)

	if len(ret) == 0 {
		panic("no return value specified for DisplayMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_DisplayMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMessage'
type MockTmuxControlPort_DisplayMessage_Call struct {
	*mock.Call
}

// DisplayMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - message string
func (_e *MockTmuxControlPort_Expecter) DisplayMessage(ctx interface{}, clientID interface{}, message interface{}) *MockTmuxControlPort_DisplayMessage_Call {
	return &MockTmuxControlPort_DisplayMessage_Call{Call: _e.mock.On("DisplayMessage", ctx, clientID, message)}
}

func (_c *MockTmuxControlPort_DisplayMessage_Call) Run(run func(ctx context.Context, clientID string, message string)) *MockTmuxControlPort_DisplayMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_DisplayMessage_Call) Return(err error) *MockTmuxControlPort_DisplayMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_DisplayMessage_Call) RunAndReturn(run func(ctx context.Context, clientID string, message string) error) *MockTmuxControlPort_DisplayMessage_Call {
	_c.Call.Return(run)
	return _c
}

// KillSession provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) KillSession(ctx context.Context, sessionName string) error {
	ret := _mock.Called(ctx, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for KillSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_KillSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSession'
type MockTmuxControlPort_KillSession_Call struct {
	*mock.Call
}

// KillSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
func (_e *MockTmuxControlPort_Expecter) KillSession(ctx interface{}, sessionName interface{}) *MockTmuxControlPort_KillSession_Call {
	return &MockTmuxControlPort_KillSession_Call{Call: _e.mock.On("KillSession", ctx, sessionName)}
}

func (_c *MockTmuxControlPort_KillSession_Call) Run(run func(ctx context.Context, sessionName string)) *MockTmuxControlPort_KillSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_KillSession_Call) Return(err error) *MockTmuxControlPort_KillSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_KillSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string) error) *MockTmuxControlPort_KillSession_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSidebarPane provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) OpenSidebarPane(ctx context.Context, clientID string, width string, command []string) (ports.PaneRef, error) {
	ret := _mock.Called(ctx, clientID, width, command)

	if len(ret) == 0 {
		panic("no return value specified for OpenSidebarPane")
	}

	var r0 ports.PaneRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) (ports.PaneRef, error)); ok {
		return returnFunc(ctx, clientID, width, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) ports.PaneRef); ok {
		r0 = returnFunc(ctx, clientID, width, command)
	} else {
		r0 = ret.Get(0).(ports.PaneRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, clientID, width, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxControlPort_OpenSidebarPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSidebarPane'
type MockTmuxControlPort_OpenSidebarPane_Call struct {
	*mock.Call
}

// OpenSidebarPane is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - width string
//   - command []string
func (_e *MockTmuxControlPort_Expecter) OpenSidebarPane(ctx interface{}, clientID interface{}, width interface{}, command interface{}) *MockTmuxControlPort_OpenSidebarPane_Call {
	return &MockTmuxControlPort_OpenSidebarPane_Call{Call: _e.mock.On("OpenSidebarPane", ctx, clientID, width, command)}
}

func (_c *MockTmuxControlPort_OpenSidebarPane_Call) Run(run func(ctx context.Context, clientID string, width string, command []string)) *MockTmuxControlPort_OpenSidebarPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_OpenSidebarPane_Call) Return(paneRef ports.PaneRef, err error) *MockTmuxControlPort_OpenSidebarPane_Call {
	_c.Call.Return(paneRef, err)
	return _c
}

func (_c *MockTmuxControlPort_OpenSidebarPane_Call) RunAndReturn(run func(ctx context.Context, clientID string, width string, command []string) (ports.PaneRef, error)) *MockTmuxControlPort_OpenSidebarPane_Call {
	_c.Call.Return(run)
	return _c
}

// RenameSession provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) RenameSession(ctx context.Context, oldName string, newName string) error {
	ret := _mock.Called(ctx, oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_RenameSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameSession'
type MockTmuxControlPort_RenameSession_Call struct {
	*mock.Call
}

// RenameSession is a helper method to define mock.On call
//   - ctx context.Context
//   - oldName string
//   - newName string
func (_e *MockTmuxControlPort_Expecter) RenameSession(ctx interface{}, oldName interface{}, newName interface{}) *MockTmuxControlPort_RenameSession_Call {
	return &MockTmuxControlPort_RenameSession_Call{Call: _e.mock.On("RenameSession", ctx, oldName, newName)}
}

func (_c *MockTmuxControlPort_RenameSession_Call) Run(run func(ctx context.Context, oldName string, newName string)) *MockTmuxControlPort_RenameSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_RenameSession_Call) Return(err error) *MockTmuxControlPort_RenameSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_RenameSession_Call) RunAndReturn(run func(ctx context.Context, oldName string, newName string) error) *MockTmuxControlPort_RenameSession_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreWindowLayout provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) RestoreWindowLayout(ctx context.Context, windowID string) error {
	ret := _mock.Called(ctx, windowID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreWindowLayout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, windowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_RestoreWindowLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreWindowLayout'
type MockTmuxControlPort_RestoreWindowLayout_Call struct {
	*mock.Call
}

// RestoreWindowLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - windowID string
func (_e *MockTmuxControlPort_Expecter) RestoreWindowLayout(ctx interface{}, windowID interface{}) *MockTmuxControlPort_RestoreWindowLayout_Call {
	return &MockTmuxControlPort_RestoreWindowLayout_Call{Call: _e.mock.On("RestoreWindowLayout", ctx, windowID)}
}

func (_c *MockTmuxControlPort_RestoreWindowLayout_Call) Run(run func(ctx context.Context, windowID string)) *MockTmuxControlPort_RestoreWindowLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_RestoreWindowLayout_Call) Return(err error) *MockTmuxControlPort_RestoreWindowLayout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_RestoreWindowLayout_Call) RunAndReturn(run func(ctx context.Context, windowID string) error) *MockTmuxControlPort_RestoreWindowLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWindowLayout provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) SaveWindowLayout(ctx context.Context, windowID string) error {
	ret := _mock.Called(ctx, windowID)

	if len(ret) == 0 {
		panic("no return value specified for SaveWindowLayout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, windowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_SaveWindowLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWindowLayout'
type MockTmuxControlPort_SaveWindowLayout_Call struct {
	*mock.Call
}

// SaveWindowLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - windowID string
func (_e *MockTmuxControlPort_Expecter) SaveWindowLayout(ctx interface{}, windowID interface{}) *MockTmuxControlPort_SaveWindowLayout_Call {
	return &MockTmuxControlPort_SaveWindowLayout_Call{Call: _e.mock.On("SaveWindowLayout", ctx, windowID)}
}

func (_c *MockTmuxControlPort_SaveWindowLayout_Call) Run(run func(ctx context.Context, windowID string)) *MockTmuxControlPort_SaveWindowLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_SaveWindowLayout_Call) Return(err error) *MockTmuxControlPort_SaveWindowLayout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_SaveWindowLayout_Call) RunAndReturn(run func(ctx context.Context, windowID string) error) *MockTmuxControlPort_SaveWindowLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchClientSession provides a mock function for the type MockTmuxControlPort
func (_mock *MockTmuxControlPort) SwitchClientSession(ctx context.Context, clientID string, sessionName string) error {
	ret := _mock.Called(ctx, clientID, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for SwitchClientSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, sessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTmuxControlPort_SwitchClientSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchClientSession'
type MockTmuxControlPort_SwitchClientSession_Call struct {
	*mock.Call
}

// SwitchClientSession is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - sessionName string
func (_e *MockTmuxControlPort_Expecter) SwitchClientSession(ctx interface{}, clientID interface{}, sessionName interface{}) *MockTmuxControlPort_SwitchClientSession_Call {
	return &MockTmuxControlPort_SwitchClientSession_Call{Call: _e.mock.On("SwitchClientSession", ctx, clientID, sessionName)}
}

func (_c *MockTmuxControlPort_SwitchClientSession_Call) Run(run func(ctx context.Context, clientID string, sessionName string)) *MockTmuxControlPort_SwitchClientSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTmuxControlPort_SwitchClientSession_Call) Return(err error) *MockTmuxControlPort_SwitchClientSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTmuxControlPort_SwitchClientSession_Call) RunAndReturn(run func(ctx context.Context, clientID string, sessionName string) error) *MockTmuxControlPort_SwitchClientSession_Call {
	_c.Call.Return(run)
	return _c
}
