// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGitPort creates a new instance of MockGitPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitPort {
	mock := &MockGitPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitPort is an autogenerated mock type for the GitPort type
type MockGitPort struct {
	mock.Mock
}

type MockGitPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitPort) EXPECT() *MockGitPort_Expecter {
	return &MockGitPort_Expecter{mock: &_m.Mock}
}

// RepoRoot provides a mock function for the type MockGitPort
func (_mock *MockGitPort) RepoRoot(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for RepoRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitPort_RepoRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoRoot'
type MockGitPort_RepoRoot_Call struct {
	*mock.Call
}

// RepoRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitPort_Expecter) RepoRoot(ctx interface{}, path interface{}) *MockGitPort_RepoRoot_Call {
	return &MockGitPort_RepoRoot_Call{Call: _e.mock.On("RepoRoot", ctx, path)}
}

func (_c *MockGitPort_RepoRoot_Call) Run(run func(ctx context.Context, path string)) *MockGitPort_RepoRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitPort_RepoRoot_Call) Return(s string, err error) *MockGitPort_RepoRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitPort_RepoRoot_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *MockGitPort_RepoRoot_Call {
	_c.Call.Return(run)
	return _c
}
