// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilesystemPort creates a new instance of MockFilesystemPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesystemPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesystemPort {
	mock := &MockFilesystemPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilesystemPort is an autogenerated mock type for the FilesystemPort type
type MockFilesystemPort struct {
	mock.Mock
}

type MockFilesystemPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesystemPort) EXPECT() *MockFilesystemPort_Expecter {
	return &MockFilesystemPort_Expecter{mock: &_m.Mock}
}

// ListImmediateDirs provides a mock function for the type MockFilesystemPort
func (_mock *MockFilesystemPort) ListImmediateDirs(root string) ([]string, error) {
	ret := _mock.Called(root)

	if len(ret) == 0 {
		panic("no return value specified for ListImmediateDirs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(root)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(root)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(root)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemPort_ListImmediateDirs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImmediateDirs'
type MockFilesystemPort_ListImmediateDirs_Call struct {
	*mock.Call
}

// ListImmediateDirs is a helper method to define mock.On call
//   - root string
func (_e *MockFilesystemPort_Expecter) ListImmediateDirs(root interface{}) *MockFilesystemPort_ListImmediateDirs_Call {
	return &MockFilesystemPort_ListImmediateDirs_Call{Call: _e.mock.On("ListImmediateDirs", root)}
}

func (_c *MockFilesystemPort_ListImmediateDirs_Call) Run(run func(root string)) *MockFilesystemPort_ListImmediateDirs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilesystemPort_ListImmediateDirs_Call) Return(strings []string, err error) *MockFilesystemPort_ListImmediateDirs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFilesystemPort_ListImmediateDirs_Call) RunAndReturn(run func(root string) ([]string, error)) *MockFilesystemPort_ListImmediateDirs_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePath provides a mock function for the type MockFilesystemPort
func (_mock *MockFilesystemPort) ResolvePath(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemPort_ResolvePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePath'
type MockFilesystemPort_ResolvePath_Call struct {
	*mock.Call
}

// ResolvePath is a helper method to define mock.On call
//   - path string
func (_e *MockFilesystemPort_Expecter) ResolvePath(path interface{}) *MockFilesystemPort_ResolvePath_Call {
	return &MockFilesystemPort_ResolvePath_Call{Call: _e.mock.On("ResolvePath", path)}
}

func (_c *MockFilesystemPort_ResolvePath_Call) Run(run func(path string)) *MockFilesystemPort_ResolvePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilesystemPort_ResolvePath_Call) Return(s string, err error) *MockFilesystemPort_ResolvePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFilesystemPort_ResolvePath_Call) RunAndReturn(run func(path string) (string, error)) *MockFilesystemPort_ResolvePath_Call {
	_c.Call.Return(run)
	return _c
}
