// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxConfigPort creates a new instance of MockTmuxConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxConfigPort {
	mock := &MockTmuxConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxConfigPort is an autogenerated mock type for the TmuxConfigPort type
type MockTmuxConfigPort struct {
	mock.Mock
}

type MockTmuxConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxConfigPort) EXPECT() *MockTmuxConfigPort_Expecter {
	return &MockTmuxConfigPort_Expecter{mock: &_m.Mock}
}

// LoadConfig provides a mock function for the type MockTmuxConfigPort
func (_mock *MockTmuxConfigPort) LoadConfig(ctx context.Context) (ports.ConfigSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 ports.ConfigSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.ConfigSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.ConfigSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.ConfigSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxConfigPort_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockTmuxConfigPort_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxConfigPort_Expecter) LoadConfig(ctx interface{}) *MockTmuxConfigPort_LoadConfig_Call {
	return &MockTmuxConfigPort_LoadConfig_Call{Call: _e.mock.On("LoadConfig", ctx)}
}

func (_c *MockTmuxConfigPort_LoadConfig_Call) Run(run func(ctx context.Context)) *MockTmuxConfigPort_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxConfigPort_LoadConfig_Call) Return(configSnapshot ports.ConfigSnapshot, err error) *MockTmuxConfigPort_LoadConfig_Call {
	_c.Call.Return(configSnapshot, err)
	return _c
}

func (_c *MockTmuxConfigPort_LoadConfig_Call) RunAndReturn(run func(ctx context.Context) (ports.ConfigSnapshot, error)) *MockTmuxConfigPort_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}
