// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClockPort creates a new instance of MockClockPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClockPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClockPort {
	mock := &MockClockPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClockPort is an autogenerated mock type for the ClockPort type
type MockClockPort struct {
	mock.Mock
}

type MockClockPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClockPort) EXPECT() *MockClockPort_Expecter {
	return &MockClockPort_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockClockPort
func (_mock *MockClockPort) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClockPort_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClockPort_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClockPort_Expecter) Now() *MockClockPort_Now_Call {
	return &MockClockPort_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClockPort_Now_Call) Run(run func()) *MockClockPort_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClockPort_Now_Call) Return(time1 time.Time) *MockClockPort_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClockPort_Now_Call) RunAndReturn(run func() time.Time) *MockClockPort_Now_Call {
	_c.Call.Return(run)
	return _c
}
