// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTmuxQueryPort creates a new instance of MockTmuxQueryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmuxQueryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmuxQueryPort {
	mock := &MockTmuxQueryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTmuxQueryPort is an autogenerated mock type for the TmuxQueryPort type
type MockTmuxQueryPort struct {
	mock.Mock
}

type MockTmuxQueryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmuxQueryPort) EXPECT() *MockTmuxQueryPort_Expecter {
	return &MockTmuxQueryPort_Expecter{mock: &_m.Mock}
}

// CurrentPanePath provides a mock function for the type MockTmuxQueryPort
func (_mock *MockTmuxQueryPort) CurrentPanePath(ctx context.Context, clientID string) (string, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentPanePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxQueryPort_CurrentPanePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPanePath'
type MockTmuxQueryPort_CurrentPanePath_Call struct {
	*mock.Call
}

// CurrentPanePath is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTmuxQueryPort_Expecter) CurrentPanePath(ctx interface{}, clientID interface{}) *MockTmuxQueryPort_CurrentPanePath_Call {
	return &MockTmuxQueryPort_CurrentPanePath_Call{Call: _e.mock.On("CurrentPanePath", ctx, clientID)}
}

func (_c *MockTmuxQueryPort_CurrentPanePath_Call) Run(run func(ctx context.Context, clientID string)) *MockTmuxQueryPort_CurrentPanePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxQueryPort_CurrentPanePath_Call) Return(s string, err error) *MockTmuxQueryPort_CurrentPanePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTmuxQueryPort_CurrentPanePath_Call) RunAndReturn(run func(ctx context.Context, clientID string) (string, error)) *MockTmuxQueryPort_CurrentPanePath_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function for the type MockTmuxQueryPort
func (_mock *MockTmuxQueryPort) ListClients(ctx context.Context) ([]ports.TmuxClientSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []ports.TmuxClientSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.TmuxClientSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.TmuxClientSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.TmuxClientSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxQueryPort_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockTmuxQueryPort_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxQueryPort_Expecter) ListClients(ctx interface{}) *MockTmuxQueryPort_ListClients_Call {
	return &MockTmuxQueryPort_ListClients_Call{Call: _e.mock.On("ListClients", ctx)}
}

func (_c *MockTmuxQueryPort_ListClients_Call) Run(run func(ctx context.Context)) *MockTmuxQueryPort_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxQueryPort_ListClients_Call) Return(tmuxClientSnapshots []ports.TmuxClientSnapshot, err error) *MockTmuxQueryPort_ListClients_Call {
	_c.Call.Return(tmuxClientSnapshots, err)
	return _c
}

func (_c *MockTmuxQueryPort_ListClients_Call) RunAndReturn(run func(ctx context.Context) ([]ports.TmuxClientSnapshot, error)) *MockTmuxQueryPort_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockTmuxQueryPort
func (_mock *MockTmuxQueryPort) ListSessions(ctx context.Context) ([]ports.TmuxSessionSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []ports.TmuxSessionSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.TmuxSessionSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.TmuxSessionSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.TmuxSessionSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxQueryPort_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockTmuxQueryPort_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxQueryPort_Expecter) ListSessions(ctx interface{}) *MockTmuxQueryPort_ListSessions_Call {
	return &MockTmuxQueryPort_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx)}
}

func (_c *MockTmuxQueryPort_ListSessions_Call) Run(run func(ctx context.Context)) *MockTmuxQueryPort_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxQueryPort_ListSessions_Call) Return(tmuxSessionSnapshots []ports.TmuxSessionSnapshot, err error) *MockTmuxQueryPort_ListSessions_Call {
	_c.Call.Return(tmuxSessionSnapshots, err)
	return _c
}

func (_c *MockTmuxQueryPort_ListSessions_Call) RunAndReturn(run func(ctx context.Context) ([]ports.TmuxSessionSnapshot, error)) *MockTmuxQueryPort_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// PaneSize provides a mock function for the type MockTmuxQueryPort
func (_mock *MockTmuxQueryPort) PaneSize(ctx context.Context, paneID string) (ports.PaneSize, error) {
	ret := _mock.Called(ctx, paneID)

	if len(ret) == 0 {
		panic("no return value specified for PaneSize")
	}

	var r0 ports.PaneSize
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PaneSize, error)); ok {
		return returnFunc(ctx, paneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PaneSize); ok {
		r0 = returnFunc(ctx, paneID)
	} else {
		r0 = ret.Get(0).(ports.PaneSize)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, paneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxQueryPort_PaneSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaneSize'
type MockTmuxQueryPort_PaneSize_Call struct {
	*mock.Call
}

// PaneSize is a helper method to define mock.On call
//   - ctx context.Context
//   - paneID string
func (_e *MockTmuxQueryPort_Expecter) PaneSize(ctx interface{}, paneID interface{}) *MockTmuxQueryPort_PaneSize_Call {
	return &MockTmuxQueryPort_PaneSize_Call{Call: _e.mock.On("PaneSize", ctx, paneID)}
}

func (_c *MockTmuxQueryPort_PaneSize_Call) Run(run func(ctx context.Context, paneID string)) *MockTmuxQueryPort_PaneSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTmuxQueryPort_PaneSize_Call) Return(paneSize ports.PaneSize, err error) *MockTmuxQueryPort_PaneSize_Call {
	_c.Call.Return(paneSize, err)
	return _c
}

func (_c *MockTmuxQueryPort_PaneSize_Call) RunAndReturn(run func(ctx context.Context, paneID string) (ports.PaneSize, error)) *MockTmuxQueryPort_PaneSize_Call {
	_c.Call.Return(run)
	return _c
}

// ServerID provides a mock function for the type MockTmuxQueryPort
func (_mock *MockTmuxQueryPort) ServerID(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ServerID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTmuxQueryPort_ServerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerID'
type MockTmuxQueryPort_ServerID_Call struct {
	*mock.Call
}

// ServerID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTmuxQueryPort_Expecter) ServerID(ctx interface{}) *MockTmuxQueryPort_ServerID_Call {
	return &MockTmuxQueryPort_ServerID_Call{Call: _e.mock.On("ServerID", ctx)}
}

func (_c *MockTmuxQueryPort_ServerID_Call) Run(run func(ctx context.Context)) *MockTmuxQueryPort_ServerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTmuxQueryPort_ServerID_Call) Return(s string, err error) *MockTmuxQueryPort_ServerID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTmuxQueryPort_ServerID_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockTmuxQueryPort_ServerID_Call {
	_c.Call.Return(run)
	return _c
}
