// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockControlPort creates a new instance of MockControlPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlPort {
	mock := &MockControlPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControlPort is an autogenerated mock type for the ControlPort type
type MockControlPort struct {
	mock.Mock
}

type MockControlPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlPort) EXPECT() *MockControlPort_Expecter {
	return &MockControlPort_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockControlPort
func (_mock *MockControlPort) CreateSession(ctx context.Context, sessionName string, path string) error {
	ret := _mock.Called(ctx, sessionName, path)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sessionName, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlPort_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockControlPort_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - path string
func (_e *MockControlPort_Expecter) CreateSession(ctx any, sessionName any, path any) *MockControlPort_CreateSession_Call {
	return &MockControlPort_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, sessionName, path)}
}

func (_c *MockControlPort_CreateSession_Call) Run(run func(ctx context.Context, sessionName string, path string)) *MockControlPort_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControlPort_CreateSession_Call) Return(err error) *MockControlPort_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlPort_CreateSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string, path string) error) *MockControlPort_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayMessage provides a mock function for the type MockControlPort
func (_mock *MockControlPort) DisplayMessage(ctx context.Context, clientID string, message string) error {
	ret := _mock.Called(ctx, clientID, message)

	if len(ret) == 0 {
		panic("no return value specified for DisplayMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlPort_DisplayMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMessage'
type MockControlPort_DisplayMessage_Call struct {
	*mock.Call
}

// DisplayMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - message string
func (_e *MockControlPort_Expecter) DisplayMessage(ctx any, clientID any, message any) *MockControlPort_DisplayMessage_Call {
	return &MockControlPort_DisplayMessage_Call{Call: _e.mock.On("DisplayMessage", ctx, clientID, message)}
}

func (_c *MockControlPort_DisplayMessage_Call) Run(run func(ctx context.Context, clientID string, message string)) *MockControlPort_DisplayMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControlPort_DisplayMessage_Call) Return(err error) *MockControlPort_DisplayMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlPort_DisplayMessage_Call) RunAndReturn(run func(ctx context.Context, clientID string, message string) error) *MockControlPort_DisplayMessage_Call {
	_c.Call.Return(run)
	return _c
}

// KillSession provides a mock function for the type MockControlPort
func (_mock *MockControlPort) KillSession(ctx context.Context, sessionName string) error {
	ret := _mock.Called(ctx, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for KillSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlPort_KillSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSession'
type MockControlPort_KillSession_Call struct {
	*mock.Call
}

// KillSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
func (_e *MockControlPort_Expecter) KillSession(ctx any, sessionName any) *MockControlPort_KillSession_Call {
	return &MockControlPort_KillSession_Call{Call: _e.mock.On("KillSession", ctx, sessionName)}
}

func (_c *MockControlPort_KillSession_Call) Run(run func(ctx context.Context, sessionName string)) *MockControlPort_KillSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControlPort_KillSession_Call) Return(err error) *MockControlPort_KillSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlPort_KillSession_Call) RunAndReturn(run func(ctx context.Context, sessionName string) error) *MockControlPort_KillSession_Call {
	_c.Call.Return(run)
	return _c
}

// RenameSession provides a mock function for the type MockControlPort
func (_mock *MockControlPort) RenameSession(ctx context.Context, oldName string, newName string) error {
	ret := _mock.Called(ctx, oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlPort_RenameSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameSession'
type MockControlPort_RenameSession_Call struct {
	*mock.Call
}

// RenameSession is a helper method to define mock.On call
//   - ctx context.Context
//   - oldName string
//   - newName string
func (_e *MockControlPort_Expecter) RenameSession(ctx any, oldName any, newName any) *MockControlPort_RenameSession_Call {
	return &MockControlPort_RenameSession_Call{Call: _e.mock.On("RenameSession", ctx, oldName, newName)}
}

func (_c *MockControlPort_RenameSession_Call) Run(run func(ctx context.Context, oldName string, newName string)) *MockControlPort_RenameSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControlPort_RenameSession_Call) Return(err error) *MockControlPort_RenameSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlPort_RenameSession_Call) RunAndReturn(run func(ctx context.Context, oldName string, newName string) error) *MockControlPort_RenameSession_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchClientSession provides a mock function for the type MockControlPort
func (_mock *MockControlPort) SwitchClientSession(ctx context.Context, clientID string, sessionName string) error {
	ret := _mock.Called(ctx, clientID, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for SwitchClientSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientID, sessionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlPort_SwitchClientSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchClientSession'
type MockControlPort_SwitchClientSession_Call struct {
	*mock.Call
}

// SwitchClientSession is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
//   - sessionName string
func (_e *MockControlPort_Expecter) SwitchClientSession(ctx any, clientID any, sessionName any) *MockControlPort_SwitchClientSession_Call {
	return &MockControlPort_SwitchClientSession_Call{Call: _e.mock.On("SwitchClientSession", ctx, clientID, sessionName)}
}

func (_c *MockControlPort_SwitchClientSession_Call) Run(run func(ctx context.Context, clientID string, sessionName string)) *MockControlPort_SwitchClientSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControlPort_SwitchClientSession_Call) Return(err error) *MockControlPort_SwitchClientSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlPort_SwitchClientSession_Call) RunAndReturn(run func(ctx context.Context, clientID string, sessionName string) error) *MockControlPort_SwitchClientSession_Call {
	_c.Call.Return(run)
	return _c
}
