// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigPort creates a new instance of MockConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigPort {
	mock := &MockConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigPort is an autogenerated mock type for the ConfigPort type
type MockConfigPort struct {
	mock.Mock
}

type MockConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigPort) EXPECT() *MockConfigPort_Expecter {
	return &MockConfigPort_Expecter{mock: &_m.Mock}
}

// LoadConfig provides a mock function for the type MockConfigPort
func (_mock *MockConfigPort) LoadConfig(ctx context.Context) (ports.ConfigSnapshot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 ports.ConfigSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.ConfigSnapshot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.ConfigSnapshot); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.ConfigSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigPort_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockConfigPort_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigPort_Expecter) LoadConfig(ctx any) *MockConfigPort_LoadConfig_Call {
	return &MockConfigPort_LoadConfig_Call{Call: _e.mock.On("LoadConfig", ctx)}
}

func (_c *MockConfigPort_LoadConfig_Call) Run(run func(ctx context.Context)) *MockConfigPort_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigPort_LoadConfig_Call) Return(configSnapshot ports.ConfigSnapshot, err error) *MockConfigPort_LoadConfig_Call {
	_c.Call.Return(configSnapshot, err)
	return _c
}

func (_c *MockConfigPort_LoadConfig_Call) RunAndReturn(run func(ctx context.Context) (ports.ConfigSnapshot, error)) *MockConfigPort_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}
