// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/tmux-session-sidebar/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataPort creates a new instance of MockMetadataPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataPort {
	mock := &MockMetadataPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataPort is an autogenerated mock type for the MetadataPort type
type MockMetadataPort struct {
	mock.Mock
}

type MockMetadataPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataPort) EXPECT() *MockMetadataPort_Expecter {
	return &MockMetadataPort_Expecter{mock: &_m.Mock}
}

// LoadSessionMetadata provides a mock function for the type MockMetadataPort
func (_mock *MockMetadataPort) LoadSessionMetadata(ctx context.Context, sessionName string) (ports.SessionMetadata, error) {
	ret := _mock.Called(ctx, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for LoadSessionMetadata")
	}

	var r0 ports.SessionMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.SessionMetadata, error)); ok {
		return returnFunc(ctx, sessionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.SessionMetadata); ok {
		r0 = returnFunc(ctx, sessionName)
	} else {
		r0 = ret.Get(0).(ports.SessionMetadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataPort_LoadSessionMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSessionMetadata'
type MockMetadataPort_LoadSessionMetadata_Call struct {
	*mock.Call
}

// LoadSessionMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
func (_e *MockMetadataPort_Expecter) LoadSessionMetadata(ctx any, sessionName any) *MockMetadataPort_LoadSessionMetadata_Call {
	return &MockMetadataPort_LoadSessionMetadata_Call{Call: _e.mock.On("LoadSessionMetadata", ctx, sessionName)}
}

func (_c *MockMetadataPort_LoadSessionMetadata_Call) Run(run func(ctx context.Context, sessionName string)) *MockMetadataPort_LoadSessionMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataPort_LoadSessionMetadata_Call) Return(sessionMetadata ports.SessionMetadata, err error) *MockMetadataPort_LoadSessionMetadata_Call {
	_c.Call.Return(sessionMetadata, err)
	return _c
}

func (_c *MockMetadataPort_LoadSessionMetadata_Call) RunAndReturn(run func(ctx context.Context, sessionName string) (ports.SessionMetadata, error)) *MockMetadataPort_LoadSessionMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSessionMetadata provides a mock function for the type MockMetadataPort
func (_mock *MockMetadataPort) SaveSessionMetadata(ctx context.Context, sessionName string, metadata ports.SessionMetadata) error {
	ret := _mock.Called(ctx, sessionName, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SaveSessionMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.SessionMetadata) error); ok {
		r0 = returnFunc(ctx, sessionName, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataPort_SaveSessionMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSessionMetadata'
type MockMetadataPort_SaveSessionMetadata_Call struct {
	*mock.Call
}

// SaveSessionMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionName string
//   - metadata ports.SessionMetadata
func (_e *MockMetadataPort_Expecter) SaveSessionMetadata(ctx any, sessionName any, metadata any) *MockMetadataPort_SaveSessionMetadata_Call {
	return &MockMetadataPort_SaveSessionMetadata_Call{Call: _e.mock.On("SaveSessionMetadata", ctx, sessionName, metadata)}
}

func (_c *MockMetadataPort_SaveSessionMetadata_Call) Run(run func(ctx context.Context, sessionName string, metadata ports.SessionMetadata)) *MockMetadataPort_SaveSessionMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ports.SessionMetadata
		if args[2] != nil {
			arg2 = args[2].(ports.SessionMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataPort_SaveSessionMetadata_Call) Return(err error) *MockMetadataPort_SaveSessionMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataPort_SaveSessionMetadata_Call) RunAndReturn(run func(ctx context.Context, sessionName string, metadata ports.SessionMetadata) error) *MockMetadataPort_SaveSessionMetadata_Call {
	_c.Call.Return(run)
	return _c
}
